apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: developer-role
rules:
- apiGroups: [""] # all API groups
  resources: ["services", "persistentvolumeclaims", "pods"] # resources to be granted permissions to
  verbs: ["*"] # all verbs or permissions
